---

#

# => Set the plugin to be enabled in a different world... to prevent plugin generated in all over the world

WORLD-ENABLE: "world"

#

# => set the Regenerate block delay! per second!

REGEN-DELAY: "5"

#

# => disable or enable send a message when player mine a spesific block!

SEND-MESSAGE: true

#

# => send a notifications when player mine the blocks and get money from it...

MINE-LOG-TYPE: true

ECONOMY-ENABLE: true

MINE-LOG-LOG: "§fYou've mined §7(§b{ore-type}§7) and gained §8+§a§l$§r§a{gained}"

##########################

#set per ores price

coal-price: "2"

iron-price: "5"

gold-price: "5"

diamond_price: "25"

emerald_price: "50"

quartz_price: "2"

lapis_price: "1"

redstone_price: "1"

stone_price: "01"

##########################

#Enable a spesific ore generate

COAL_ORE: true

IRON_ORE: true

GOLD_ORE: true

DIAMOND_ORE: true

EMERALD_ORE: true

QUARTZ_ORE: true

LAPIS_ORE: true

REDSTONE_ORE: true

STONE: true

...

